# Variables

#This is a comment - any code commented out is not run -
#meaning that any code or text commented out is ignored.

"""
this is a multi-line comment
You can comment out many lines at once.
For the most part you will see single line comments
but it is good to see this.
As in single line comments, any code contained within multi-line comments are not run -
meaning that any code commented out is ignored.
"""

## Topic: Strings

Create a variable named `subject` with no value (None)


In [1]:
subject = None
subject

Assign a value of "Programmers to the variable `subject`.


In [2]:
subject = "Programmers"
subject

'Programmers'

Create a variable, `first_name`, and assign it a value of an empty string.

In [3]:
first_name = ""
first_name

''

Assign a value of "Ada" to the variable `first_name`.

In [4]:
first_name = "Ada"
first_name

'Ada'

Create a variable, `last_name`, and assign it a value of a string, "Lovelace".

In [5]:
last_name = "Lovelace"
last_name

'Lovelace'

Create a variable, `full_name`, and assign it a value of the combination of `first_name` and `last_name` with a space.

In [6]:
full_name = f"{first_name} {last_name}"
full_name

'Ada Lovelace'

Create a variable, `profession`, and assign it a value of a string, "Computer Programmer".

In [7]:
profession = "Computer Programmer"
profession

'Computer Programmer'

Create a variable, `known_for`, and assign it a value of a string, "First Computer Programmer".

In [8]:
known_for = "First Computer Programmer"
known_for

'First Computer Programmer'

Create a variable, `first_algorithm`, and assign it a value of a string, "Analytical Engine".

In [9]:
first_algorithm = "Analytical Engine"
first_algorithm

'Analytical Engine'

Create a variable, `city_location`, and assign it a value of a string, "London".

In [10]:
city_location = "London"
city_location

'London'

Create a variable, `country_location`, and assign it a value of a string, "England".

In [11]:
country_location = "England"
country_location

'England'

Create a variable, `nationality`, and assign it a value of a string, "British".

In [12]:
nationality = "British"
nationality

'British'

## Topic: Integers

Create a variable, `birth_year`, and assign it with an integer of 1815.


In [13]:
birth_year = 1815
birth_year

1815

Create a variable, `death_year`, and assign it with an integer of 1852.

In [14]:
death_year = 1852
death_year

1852

Create a variable, `age_at_passing`, and assign it a value of death_year minus birth_year.

In [15]:
age_at_passing = 37
age_at_passing

37

Create a variable, `year_of_publish`, and assign it with an integer of 1842.

In [16]:
year_of_publish = 1842
year_of_publish

1842

## Topic: Print

- Print: "First Name: " and `first_name`.
- Print: "Last Name: " and `last_name`.
- Print: "Profession: " and `profession`.
- Print: "BirthYear: " and `birth_year`.


In [17]:
print(f"First Name: {first_name}")
print(f"Last Namr: {last_name}")
print(f"Profession: {profession}")
print(f"BirthYear: {birth_year}")

First Name: Ada
Last Namr: Lovelace
Profession: Computer Programmer
BirthYear: 1815


## Topic: Concat Values

Create and print a variable, `statement_one`, by assigning it a value of a concatenated string:

"Programmers: Ada Lovelace is a British Computer Programmer born in 1815."


In [18]:
statement_one = f"{subject}: {first_name} {last_name} is a {nationality} {profession} born in {birth_year}."
print(statement_one)

Programmers: Ada Lovelace is a British Computer Programmer born in 1815.


Create and print a variable, `statement_two`, by assigning it a value of a concatenated string:

"She is commonly referred to as the First Computer Programmer."

In [19]:
statement_two = f"She is commonly referred to as the {known_for}."
print(statement_two)

She is commonly referred to as the First Computer Programmer.


Create and print a variable, `statement_three`, by assigning it a value of a concatenated string:

"In 1842 she published the first Algorithm, the Analytical Engine, at the age of 27."

In [20]:
statement_three = f"In {year_of_publish}, she published the first Algorithm, the {first_algorithm}, at the age of 37."
print(statement_three)

In 1842, she published the first Algorithm, the Analytical Engine, at the age of 37.


Create and print a variable, `statement_four`, by assigning it a value of a concatenated string:

"She was a British Citizen who lived in London, England until her passing in 1852 at the age of 37."

In [21]:
statement_four = f"She was a {nationality} Citizen who lived in {city_location}, {country_location} until her passing in {death_year} at the age of {age_at_passing}."
print(statement_four)

She was a British Citizen who lived in London, England until her passing in 1852 at the age of 37.
